---
- hosts: all
  become: true
  tasks:

    - name: This command will execute apt updates
      ansible.builtin.shell: sudo apt-get update -y
      args:
        executable: /bin/bash 

    - name: This command will execute apt upgrades
      ansible.builtin.shell: sudo apt-get upgrade -y
      args:
        executable: /bin/bash  

    - name: This command will execute apt-dist upgrades
      ansible.builtin.shell: sudo apt-get dist-upgrade -y
      args:
        executable: /bin/bash  
